// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace WellingtonTrains.Web {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label lblLine;
		
		protected System.Web.UI.WebControls.DropDownList DropDownListLines;
		
		protected System.Web.UI.WebControls.Label lblFrom;
		
		protected System.Web.UI.WebControls.DropDownList DropDownListFrom;
		
		protected System.Web.UI.WebControls.Label lblTo;
		
		protected System.Web.UI.WebControls.DropDownList DropDownListTo;
		
		protected System.Web.UI.WebControls.Label lblDay;
		
		protected System.Web.UI.WebControls.DropDownList DropDownListDay;
		
		protected System.Web.UI.WebControls.LinkButton ButtonLookup;
		
		protected System.Web.UI.WebControls.Literal literalLink;
		
		protected System.Web.UI.WebControls.HiddenField lineSelection;
		
		protected System.Web.UI.WebControls.HiddenField fromSelection;
		
		protected System.Web.UI.WebControls.HiddenField toSelection;
		
		protected System.Web.UI.WebControls.HiddenField daySelection;
		
		protected System.Web.UI.WebControls.Table TableTimes;
	}
}
